### ISSUE TITLE
Static Line waypoint doesn't work when spawned via script.

### ISSUE THREAD

**Issue by clbt404** [DartRuffian/AimForTheBushes#25]
## Describe the bug
The Static Line waypoint doesn't seem to work correctly when I spawn it with the addWaypoint and setWaypointType commands. As the plane gets to the waypoint it starts doing circles.

## To reproduce
1. Create a script that creates a waypoint for the spawned plane.
2. Run said script.
3. Observe plane flying towards the waypoint and start doing circles.

## Expected behavior
I expect to be paradropped when the plane reaches the LZ. (AI dropping players is enabled in the settings and works correctly when done in 3den.)

## Attachments
Script used to spawn the plane and waypoints:
https://pastebin.com/qnN61SXg

**Comment by DartRuffian** [comment]
I'm not sure if custom waypoints can be created with `setWaypointType`. Wiki page for it doesn't mention anything, so the game might just default to a `MOVE` waypoint, which would explain why the plane just moves in circles.

If custom waypoints can't be created directly, I can update [fnc_jumpAIWaypoint](https://github.com/DartRuffian/AimForTheBushes/blob/main/addons/staticline/functions/fnc_jumpAIWaypoint.sqf) to be a part of the public API and then you can just call that.

**Comment by DartRuffian** [comment]
@clbt404 You may have seen it in the ace discord, but try doing:
```sqf
private _wpt1 = _planeGrp addWaypoint [getMarkerPos _dropZone, 0, 1];
_wpt1 setWaypointType "SCRIPTED";
_wpt1 setWaypointScript "z\aftb\addons\staticline\functions\fnc_jumpaiwaypoint.sqf";
```
```

**Comment by clbt404** [comment]
I'll try that

**Comment by clbt404** [comment]
Well, that didn't work either. It's weird that the plane flies like it should to the LZ, but without deploying the player, and then circling without completing the waypoint.

**Comment by DartRuffian** [comment]
Are you sure the deploy players setting is enabled?
I just tested using this exact script without any issues.
```sqf
private _plane = createVehicle ["B_T_VTOL_01_infantry_F", getMarkerPos "marker_0", [], 0, "FLY"]; 
private _planeGrp = createVehicleCrew _plane; 
  
private _wpt1 = _planeGrp addWaypoint [getMarkerPos "marker_1", 0, 1]; 
_wpt1 setWaypointType "SCRIPTED"; 
_wpt1 setWaypointScript "z\aftb\addons\staticLine\functions\fnc_jumpAIWaypoint.sqf";
```

**Comment by DartRuffian** [comment]
You could also share your mission and modlist

**Comment by clbt404** [comment]
Something with the RHS C-130 maybe? In either my full script or the bare bones through debug console, it did not work. The Vanilla Blackfish worked fine.

**Comment by DartRuffian** [comment]
What seat are you sitting in?

**Comment by clbt404** [comment]
Sure, here or Discord?

**Comment by clbt404** [comment]
Roger, wait a minute.

**Comment by clbt404** [comment]
Sent

**Comment by DartRuffian** [comment]
The main mods that stick out to me are LAMBS soley because it's an AI mod, but I'm not familiar with how much / what it changes on the technical level.

**Comment by clbt404** [comment]
Same result with just: CBA, ACE, RHSUSAF, AFTB, ZEN, on fresh Altis mission.

**Comment by DartRuffian** [comment]
That's very strange
I took one of the existing C-130Js in your mission and removed the disable simulation command, worked fine

**Comment by DartRuffian** [comment]
Try watching the `aftb_staticLine_unitsToDeploy` variable on whatever vehicle is doing the insertion. It should be an array of units that the vehicle will deploy, and a unit is removed from it each time they jump

**Comment by clbt404** [comment]
> That's very strange I took one of the existing C-130Js in your mission and removed the disable simulation command, worked fine

For some odd reason the ones placed in 3den worked just fine for me, but the ones spawned in-game did not. I'm going to fully wipe to mod installation and try again.

**Comment by clbt404** [comment]
Well, I guess I got a clue. When I placed the plane, waypoint and a character into the cargo, I got dropped from the C130, but same setup but teleporting the player into the cargo with "moveInCargo" command, it did not work.

**Comment by DartRuffian** [comment]
> Try watching the `aftb_staticLine_unitsToDeploy` variable on whatever vehicle is doing the insertion. It should be an array of units that the vehicle will deploy, and a unit is removed from it each time they jump

Did you try doing this to see what units are being included?
Also, if AI units are moved in, are they dropped?

**Comment by clbt404** [comment]
> > Try watching the `aftb_staticLine_unitsToDeploy` variable on whatever vehicle is doing the insertion. It should be an array of units that the vehicle will deploy, and a unit is removed from it each time they jump

Not quite sure how to do so. I'll try again with some AI's.

**Comment by clbt404** [comment]
Now I'm starting to get confused. Suddenly after rebooting the game the WP works...

1. Plane and player placed in editor
2. Plane spawned with script and player teleported in
3. Plane spawned in editor and player teleported in

What is the matter with this game

**Comment by clbt404** [comment]
Ok so, got some data about the issue as it persists on. It seems that there's some problems with the jumpInterVal, as my friend tested it and got a result of 90 seconds between jumps, also 90 seconds of circling the waypoint.

Scripts used to test
`private _plane = createVehicle ["B_Heli_Transport_03_F", getMarkerPos "marker_0", [], 0, "FLY"]; 
private _planeGrp = createVehicleCrew _plane;
for "_i" from 0 to 6 do {
    _unit = _planeGrp createUnit [typeOf driver _plane, _planeGrp, [], 0, "CARGO"];
}; `
  
`private _wpt1 = _planeGrp addWaypoint [getMarkerPos "marker_1", 0, 1]; 
_wpt1 setWaypointType "SCRIPTED"; 
_wpt1 setWaypointScript "z\aftb\addons\staticLine\functions\fnc_jumpAIWaypoint.sqf";`

Test data on the jumpInterVal
`21:03:10 [AFTB] (staticLine) TRACE: 25599 _time TIME: 2000=2000, (speed _vehicle)=11.7775, _time=611.337 z\aftb\addons\staticline\functions\fnc_jumpAI.sqf:47
21:03:10 [AFTB] (staticLine) TRACE: 25601 _jumpInterVal COUNT: count _unitsToDeploy=7, _jumpInterval=87.3338 z\aftb\addons\staticline\functions\fnc_jumpAI.sqf:48`


`21:32:39 [AFTB] (staticLine) TRACE: 16713 fnc_createParachute: _unit=B Alpha 1-4:5, _parachuteClass=NonSteerable_Parachute_F z\aftb\addons\staticline\functions\fnc_createParachute.sqf:21
21:33:57 [AFTB] (staticLine) TRACE: 18913 fnc_getOutMan:`

**Comment by clbt404** [comment]
Also on the example provided in fnc_jumpAIWaypoint it says to `call` the function, but as it is scheduled it cannot be called without errors.

**Comment by DartRuffian** [comment]
> Also on the example provided in fnc_jumpAIWaypoint it says to `call` the function, but as it is scheduled it cannot be called without errors.

I'll correct it, it's only scheduled because A3 runs waypoints scheduled.
I had planned on rewriting it to run unscheduled before release but it was a huge pain.

**Comment by DartRuffian** [comment]
As for the interval, it's based on the number on the units that will be jumping, the speed of the vehicle, and the distance to deploy units over (always 2km).

With your logs, you have the vehicle moving at 11 km/h, which is incredibly slow. So it tries to average units out along that entire route.

https://github.com/DartRuffian/AimForTheBushes/blob/main/addons/staticline/functions/fnc_jumpAI.sqf#L45

**Comment by clbt404** [comment]
That's really weird, tho that happened on my friends testing, for me it also happens no matter the speed, default WP behaivior or custom set, works fine via editor, via script not.

**Comment by DartRuffian** [comment]
> That's really weird, tho that happened on my friends testing, for me it also happens no matter the speed, default WP behaivior or custom set, works fine via editor, via script not.

Test your same setup on the dev build
https://steamcommunity.com/sharedfiles/filedetails/?id=3312012350

**Comment by DartRuffian** [comment]
Also when posting code / small logs, use code blocks instead of in-line code.

\`\`\`
log
\`\`\`
